// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type CreateWorkflowReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
}

type CreateWorkflowResp struct {
	Id int64 `json:"id"`
}

type DeleteWorkflowReq struct {
	Id int64 `path:"id"`
}

type DeleteWorkflowResp struct {
}

type GetWorkflowReq struct {
	Id int64 `path:"id"`
}

type GetWorkflowResp struct {
	Workflow Workflow `json:"workflow"`
}

type HealthReq struct {
}

type HealthResp struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

type ListWorkflowsReq struct {
	Page     int `form:"page,optional,default=1"`
	PageSize int `form:"page_size,optional,default=20"`
}

type ListWorkflowsResp struct {
	Total     int64      `json:"total"`
	Workflows []Workflow `json:"workflows"`
}

type UpdateWorkflowReq struct {
	Id          int64  `path:"id"`
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
}

type UpdateWorkflowResp struct {
}

type Workflow struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Status      int    `json:"status"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}
