// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	workflowRunStepsFieldNames          = builder.RawFieldNames(&WorkflowRunSteps{})
	workflowRunStepsRows                = strings.Join(workflowRunStepsFieldNames, ",")
	workflowRunStepsRowsExpectAutoSet   = strings.Join(stringx.Remove(workflowRunStepsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	workflowRunStepsRowsWithPlaceHolder = strings.Join(stringx.Remove(workflowRunStepsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	workflowRunStepsModel interface {
		Insert(ctx context.Context, data *WorkflowRunSteps) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*WorkflowRunSteps, error)
		FindOneByRunIdNodeId(ctx context.Context, runId uint64, nodeId string) (*WorkflowRunSteps, error)
		Update(ctx context.Context, data *WorkflowRunSteps) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultWorkflowRunStepsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WorkflowRunSteps struct {
		Id           uint64         `db:"id"`
		RunId        uint64         `db:"run_id"`
		NodeId       string         `db:"node_id"`     // Node ID from definition
		NodeType     string         `db:"node_type"`   // script|http|human|etc
		NodeConfig   sql.NullString `db:"node_config"` // Node configuration snapshot
		Status       string         `db:"status"`      // pending|running|succeeded|failed|waiting_human|skipped
		InputData    sql.NullString `db:"input_data"`  // Input data for this step
		OutputData   sql.NullString `db:"output_data"` // Output data from this step
		ErrorMessage sql.NullString `db:"error_message"`
		StartedAt    sql.NullTime   `db:"started_at"`
		FinishedAt   sql.NullTime   `db:"finished_at"`
		CreatedAt    time.Time      `db:"created_at"`
		UpdatedAt    time.Time      `db:"updated_at"`
	}
)

func newWorkflowRunStepsModel(conn sqlx.SqlConn) *defaultWorkflowRunStepsModel {
	return &defaultWorkflowRunStepsModel{
		conn:  conn,
		table: "`workflow_run_steps`",
	}
}

func (m *defaultWorkflowRunStepsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultWorkflowRunStepsModel) FindOne(ctx context.Context, id uint64) (*WorkflowRunSteps, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", workflowRunStepsRows, m.table)
	var resp WorkflowRunSteps
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWorkflowRunStepsModel) FindOneByRunIdNodeId(ctx context.Context, runId uint64, nodeId string) (*WorkflowRunSteps, error) {
	var resp WorkflowRunSteps
	query := fmt.Sprintf("select %s from %s where `run_id` = ? and `node_id` = ? limit 1", workflowRunStepsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, runId, nodeId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWorkflowRunStepsModel) Insert(ctx context.Context, data *WorkflowRunSteps) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, workflowRunStepsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.RunId, data.NodeId, data.NodeType, data.NodeConfig, data.Status, data.InputData, data.OutputData, data.ErrorMessage, data.StartedAt, data.FinishedAt)
	return ret, err
}

func (m *defaultWorkflowRunStepsModel) Update(ctx context.Context, newData *WorkflowRunSteps) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, workflowRunStepsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.RunId, newData.NodeId, newData.NodeType, newData.NodeConfig, newData.Status, newData.InputData, newData.OutputData, newData.ErrorMessage, newData.StartedAt, newData.FinishedAt, newData.Id)
	return err
}

func (m *defaultWorkflowRunStepsModel) tableName() string {
	return m.table
}
