// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	workflowRunsFieldNames          = builder.RawFieldNames(&WorkflowRuns{})
	workflowRunsRows                = strings.Join(workflowRunsFieldNames, ",")
	workflowRunsRowsExpectAutoSet   = strings.Join(stringx.Remove(workflowRunsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	workflowRunsRowsWithPlaceHolder = strings.Join(stringx.Remove(workflowRunsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	workflowRunsModel interface {
		Insert(ctx context.Context, data *WorkflowRuns) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*WorkflowRuns, error)
		Update(ctx context.Context, data *WorkflowRuns) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultWorkflowRunsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WorkflowRuns struct {
		Id                 uint64         `db:"id"`
		WorkflowId         uint64         `db:"workflow_id"`
		WorkflowVersion    uint64         `db:"workflow_version"`    // Version of workflow at run time
		DefinitionSnapshot string         `db:"definition_snapshot"` // Frozen workflow definition
		Status             string         `db:"status"`              // pending|running|succeeded|failed|cancelled
		TriggerType        string         `db:"trigger_type"`        // manual|schedule|webhook
		StartedAt          sql.NullTime   `db:"started_at"`
		FinishedAt         sql.NullTime   `db:"finished_at"`
		ErrorMessage       sql.NullString `db:"error_message"`
		CreatedAt          time.Time      `db:"created_at"`
		UpdatedAt          time.Time      `db:"updated_at"`
	}
)

func newWorkflowRunsModel(conn sqlx.SqlConn) *defaultWorkflowRunsModel {
	return &defaultWorkflowRunsModel{
		conn:  conn,
		table: "`workflow_runs`",
	}
}

func (m *defaultWorkflowRunsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultWorkflowRunsModel) FindOne(ctx context.Context, id uint64) (*WorkflowRuns, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", workflowRunsRows, m.table)
	var resp WorkflowRuns
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWorkflowRunsModel) Insert(ctx context.Context, data *WorkflowRuns) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, workflowRunsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.WorkflowId, data.WorkflowVersion, data.DefinitionSnapshot, data.Status, data.TriggerType, data.StartedAt, data.FinishedAt, data.ErrorMessage)
	return ret, err
}

func (m *defaultWorkflowRunsModel) Update(ctx context.Context, data *WorkflowRuns) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, workflowRunsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.WorkflowId, data.WorkflowVersion, data.DefinitionSnapshot, data.Status, data.TriggerType, data.StartedAt, data.FinishedAt, data.ErrorMessage, data.Id)
	return err
}

func (m *defaultWorkflowRunsModel) tableName() string {
	return m.table
}
