// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	"backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Health check endpoint
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthHandler(serverCtx),
			},
			{
				// List all workflows
				Method:  http.MethodGet,
				Path:    "/workflows",
				Handler: ListWorkflowsHandler(serverCtx),
			},
			{
				// Create a new workflow
				Method:  http.MethodPost,
				Path:    "/workflows",
				Handler: CreateWorkflowHandler(serverCtx),
			},
			{
				// Get workflow by ID
				Method:  http.MethodGet,
				Path:    "/workflows/:id",
				Handler: GetWorkflowHandler(serverCtx),
			},
			{
				// Update workflow
				Method:  http.MethodPut,
				Path:    "/workflows/:id",
				Handler: UpdateWorkflowHandler(serverCtx),
			},
			{
				// Delete workflow
				Method:  http.MethodDelete,
				Path:    "/workflows/:id",
				Handler: DeleteWorkflowHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
