// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	"backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Health check endpoint
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthHandler(serverCtx),
			},
			{
				// Get run details
				Method:  http.MethodGet,
				Path:    "/runs/:runId",
				Handler: GetRunHandler(serverCtx),
			},
			{
				// SSE stream for run events
				Method:  http.MethodGet,
				Path:    "/runs/:runId/events",
				Handler: GetRunEventsHandler(serverCtx),
			},
			{
				// Get run steps
				Method:  http.MethodGet,
				Path:    "/runs/:runId/steps",
				Handler: GetRunStepsHandler(serverCtx),
			},
			{
				// List all workflows
				Method:  http.MethodGet,
				Path:    "/workflows",
				Handler: ListWorkflowsHandler(serverCtx),
			},
			{
				// Create a new workflow
				Method:  http.MethodPost,
				Path:    "/workflows",
				Handler: CreateWorkflowHandler(serverCtx),
			},
			{
				// Get workflow by ID including nodes/edges
				Method:  http.MethodGet,
				Path:    "/workflows/:id",
				Handler: GetWorkflowHandler(serverCtx),
			},
			{
				// Update/save workflow definition
				Method:  http.MethodPut,
				Path:    "/workflows/:id",
				Handler: UpdateWorkflowHandler(serverCtx),
			},
			{
				// Delete workflow (draft only)
				Method:  http.MethodDelete,
				Path:    "/workflows/:id",
				Handler: DeleteWorkflowHandler(serverCtx),
			},
			{
				// Disable workflow (enabled -> disabled)
				Method:  http.MethodPost,
				Path:    "/workflows/:id/disable",
				Handler: DisableWorkflowHandler(serverCtx),
			},
			{
				// Enable workflow (draft|disabled -> enabled)
				Method:  http.MethodPost,
				Path:    "/workflows/:id/enable",
				Handler: EnableWorkflowHandler(serverCtx),
			},
			{
				// Trigger a workflow run (draft allowed)
				Method:  http.MethodPost,
				Path:    "/workflows/:id/runs",
				Handler: TriggerRunHandler(serverCtx),
			},
			{
				// List runs by workflow
				Method:  http.MethodGet,
				Path:    "/workflows/:id/runs",
				Handler: ListRunsByWorkflowHandler(serverCtx),
			},
			{
				// Validate workflow structure
				Method:  http.MethodPost,
				Path:    "/workflows/:id/validate",
				Handler: ValidateWorkflowHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
